# Generated by Django 3.2.5 on 2022-04-16 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='pk',
        ),
    ]
